config/routes.rb
EventerApp::Application.routes.draw do
  get "volunteers/new"
  get "volunteers/index"
  get "volunteers/edit"
  get "volunteers/show"
  get "static_pages/learn"
  devise_for :users 
  resources :users do 
    resources :events do 
      resources :items do 
        resources :volunteers
      end
    end
  end

  root 'static_pages#home'

  

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :eventable, polymorphic: true
  has_attached_file :photo, :dependent => :destroy
  geocoded_by :address
  after_validation :geocode
  has_many :items, as: :itemable, :dependent => :destroy
  has_many :volunteers, as: :volunteerable, :dependent => :destroy
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :itemable, polymorphic: true
  has_many :volunteers, as: :volunteerable, :dependent => :destroy
  validates :name, :presence => true
  validates :quantity_needed, :presence => true
  validates_numericality_of :quantity_needed, :on => :create
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_attached_file :profile_pic, dependent: :destroy
  has_many :events, as: :eventable, dependent: :destroy
  has_many :items, as: :itemable, dependent: :destroy
  has_many :volunteers, as: :volunteerable, :dependent => :destroy
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	belongs_to :volunteerable, polymorphic: true
  has_attached_file :profile_pic
  def item_quantity_have
  	a = self.volunteerable
  	a.quantity_have
  end

  def item_quantity_given
    self.quantity_given
  end

  def item_quantity_needed
    a = self.volunteerable
    a.quantity_needed
  end

  def add_em_up
    item_quantity_given + item_quantity_have.to_i  
  end

  def subtract_em_down
    item_quantity_needed.to_i - item_quantity_given
  end

  def make_it_happen
  	a = self.volunteerable
    if item_quantity_have.to_i != item_quantity_needed.to_i
  	  a.update_attributes(quantity_have: add_em_up)
    else
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :profile_pic) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :profile_pic) }
  end  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :load_eventable

  def show
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    @items = @event.items(:created_at).order("created_at desc")
  end

  def new
    @user = User.find(params[:user_id])
  	@event = @eventable.events.new
    @events = @user.events
    @items = @user.items
  end

  def update
    @user = User.find(params[:user_id])
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to user_event_path(@user, @event), notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      end
    end	
  end

  def create
    @user = User.find(params[:user_id])
    @events = @user.events
    @event = @eventable.events.create!(event_params)
    if @event.save
      respond_to do |format|
        format.html { redirect_to user_event_path(@user, @event)}
        format.js
      end  
    else
      render :new
    end
  end

  def edit
  	@event = Event.find(params[:id])
  end

  def destroy 
  	@event = Event.find(params[:id])
  	@event.destroy 
	  respond_to do |format|
	  format.html { redirect_to new_user_event_path }
	  format.js
    end
  end
private
  def event_params
    params.require(:event).permit(:name, :date_time, :photo, :organization_name, :venue, :description, :address, :latitude, :longitude)
  end
  def load_eventable
    resource, id = request.path.split('/')[1,2]
    @eventable = resource.singularize.classify.constantize.find(id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :load_itemable
  before_filter :event_show_page

  def show
    @item = Item.find(params[:id])
  end

  def new
    @eventable = Event.find(params[:event_id])
  	@item = @itemable.items.new
  end

  def create
    @user = User.find(params[:user_id])
    @itemable = Event.find(params[:event_id])
    @items = @itemable.items(:created_at).order("created_at desc")
    @item = @itemable.items.new(item_params)
    if @item.save
      respond_to do |format|
        format.html { redirect_to user_event_path(@user, @itemable) }
        format.js
      end
    else
      render :new
    end
  end

  def update
    @user = User.find(params[:user_id])
    @itemable = Event.find(params[:event_id])

    @item = Item.find(params[:id])
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to user_event_path(@user, @itemable), notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      end
    end	
  end

  def edit
  end

  def destroy
    @user = User.find(params[:user_id])
    @itemable = Event.find(params[:event_id])

    @item = Item.find(params[:id])
    @item.destroy
    redirect_to user_event_path(@user, @itemable)
  end 

private
  def item_params
    params.require(:item).permit(:name, :quantity_have, :quantity_needed)
  end
  def load_itemable
    resource, id = request.path.split('/')[1,2]
    @itemable = resource.singularize.classify.constantize.find(id)
  end

  def event_show_page
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	def show
	  @user = User.find(params[:id])
    @events = @user.events
    @item = @user.items
	end

	def edit
	  @user = User.find(params[:id])
	end

	def update
	  @user = User.find(params[:id])
      respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to current_user, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      end
    end
	end

  def destroy 
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end
private
  def user_params
    params.require(:user).permit(:name, :email, :profile_pic)
  end
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
  before_filter :load_volunteerable
  def new
  	@events = Event.find(params[:event_id])
  	@items = Item.find(params[:item_id])
  	@volunteer = @volunteerable.volunteers.new
  end

  def create
  	@user = User.find(params[:user_id])
  	@event = Event.find(params[:event_id])
  	@item = Item.find(params[:item_id])
    @items = @event.items(:created_at).order("created_at desc")
    @volunteer = @item.volunteers.create!(volunteer_params)
    if @volunteer.save
      respond_to do |format|
        format.html { redirect_to user_event_path(@user, @event, @volunteer)}
        format.js
      end  
      @volunteer.make_it_happen
    else
      render :new
    end
  end

  def index
  end

  def edit
  end

  def show
  end
private
  def volunteer_params
    params.require(:volunteer).permit(:name, :email, :phone, :quantity_given, :profile_pic)
  end
  def load_volunteerable
    resource, id = request.path.split('/')[1,2]
    @volunteerable = resource.singularize.classify.constantize.find(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def show_user_bg
  	if @events.photo.file?
      "background:url(#{@events.photo.url}) no-repeat fixed left top; background-size: cover; background-position:right bottom; "    
    else
      "background: #3e3e3e;"
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/events/_event.html.haml
.span10{style: 'margin: 0;'}
	%h3
		= @event.name
		- if current_user
		- else
			= link_to 'Edit', edit_user_event_path(@event.eventable, @event), class: 'btn-small btn-warning'
			= link_to 'Delete', user_event_path(@event.eventable, @event), class: 'btn-small btn-danger', method: :delete

	.span3{style: 'position: relative; top: 0px;'}

app/views/events/create.js.erb
$('.event-creator-box').html('<%= j render("events/event") %>').hide().fadeIn('slow');

app/views/events/edit.html.haml
%h1 Edit
= form_for [@eventable, @event] do |f|
	= f.label :name
	= f.text_field :name
	= f.label :photo
	= f.file_field :photo
	= f.submit
	

app/views/events/new.html.haml
.container{style: 'margin-top: 80px;'}
	.event-creator-box
		.row.create-box{style: 'margin-left: 50px;'}
			.span6
				= form_for [@user, @event], :html => {:multipart => true} do |f|
					%h3 Create Your Event!
					= f.label 'Give your event an awsome name'
					= f.text_field :name, placeholder: 'e.g. Super Awsome Party!'
					= f.label 'Organization Name'
					= f.text_field :organization
					= f.label 'Venue Name'
					= f.text_field :venue
					= f.label "Date of Event"
					= f.date_field :date_time
					%br
					%br
					= f.label "Address"
					= f.text_field :address
					= f.label 'Upload a Photo of your Event'
					= image_tag 'default_upload_logo.gif', style: 'float: left;'
					= f.file_field :photo, style: 'width: 180px !important; margin-left: 10px;'
					.span{style: 'font-size: 12px; position: relative; right: 20px;'}
						Your image must be JPG, GIF, or PNG format and not exceed 2MB. It will be resized to make its width 450px.
					%br
					%br
					%br
					%br
					%br
					= f.label :description
					= f.text_area :description, style: 'width: 570px; height: 200px;'
					%br
					%br
					= f.submit 'Create Event', class: 'btn-large btn-primary create-event'
					By Clicking on this button you are accepting our Terms of Services

app/views/events/new.js.erb
$('.create-event').hide().after('<%= j render("events/form") %>');

app/views/events/show.html.haml
%br
%br
%br
%br
.container
	.row
		.span7
			%h3
				= @event.name 
				(
				= @event.date_time.strftime("%A, %B %d %Y")
				)
			.event-photo{style: 'width: 100%;'}
				- if @event.photo.file?
					= image_tag @event.photo, style: 'width: 100%;'
				- else
					%h3 Upload an Image for your Event
					= link_to 'upload image'
			.created-event
				- if current_user
					= link_to "Add Items", new_user_event_item_path(@eventable, @event, @items), class: 'btn-small btn-success add-items', remote: true
				.created-items
					= render 'items/item'
		%br
		%br
		%br
		.span4
			%ul.thumbnails
				%li.span4
					.thumbnail
						= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}"
						%br
						%strong
							= @event.venue
						%br
						= @event.address
						%br
						%br
						= @event.date_time.strftime("%A, %B %d %Y")
					%br
					= @event.description

.add-item-form-container

app/views/items/_form.html.haml
= form_for [@itemable, @eventable, @items] do |f|
	= f.label :name
	= f.text_field :name
	= f.label :quantity_needed
	= f.text_field :quantity_needed
	= f.submit

app/views/items/_item.html.haml
#table
	- @items.each do |item|
		%br
		%br
		.line{style: 'border-top: solid #cfcfcf 1px;'}
		%br
		.first_row{style: 'text-align: left; width: 20%; float: left; margin-right: 20%; font-weight: bold;'}
			= item.name
		.second_row{style: 'text-align: center; width: 10%; float: left; margin-right: 15%;'}
			= item.quantity_have.to_i
		.third_row{style: 'text-align: center; width: 10%; float: left; margin-right: 15%;'}
			= item.quantity_needed.to_i
		.fourth_row{style: 'text-align: center; width: 10%; float: left;'}
			= link_to 'Volunteer', new_user_event_item_volunteer_path(@eventable, @event, item), class: 'btn-small btn-info add-items create-volunteer', remote: true

		.div{id:"volunteer-#{item.id}", style: 'margin-top: 5px; margin-left: 20px;'}
		- item.volunteers.each do |volunteers|
			%ul{style: 'margin-left: 10px; margin-bottom: -20px;'}
				%br
				%br
				%li{style: 'line-height: 1px; font-style:italic; letter-spacing: 2px;'}
					= volunteers.name
					is bringing 
					= volunteers.quantity_given.to_i
					= item.name
			%br
			%br
		





/ %table.table{style: 'margin: 0;'}
/ 	%thead
/ 		%th Item Name
/ 		%th Quantity Given
/ 		%th Quantity Needed
/ 	%tbody.items-container
/ 		- @items.each do |item|
/ 			%tr
/ 				%td
/ 					%strong
/ 						= item.name
/ 				%td= item.quantity_have.to_i
/ 				%td= item.quantity_needed.to_i
/ 				- if current_user
/ 					%td= link_to 'edit', edit_user_event_item_path(@eventable, @event, item), class: 'btn-small btn-warning add-items'
/ 					%td= link_to 'delete', user_event_item_path(@eventable, @event, item), class: 'btn-small btn-danger add-items', method: :delete
/ 				- if item.quantity_needed.to_i == item.quantity_have.to_i
/ 					%td{style: 'color: green; font-weight: bold;'} Complete!
/ 				- else
/ 					%td= link_to 'Volunteer', new_user_event_item_volunteer_path(@eventable, @event, item), class: 'btn-small btn-info add-items create-volunteer', remote: true
/ 			%tr
/ 				%td{style: 'border-top: none;'}
/ 					.div{id:"volunteer-#{item.id}"}
/ 					- item.volunteers.each do |volunteers|

/ 						= volunteers.name
/ 						is giving
/ 						= volunteers.quantity_given
/ 						%br

app/views/items/_new.html.haml
.item-add-popup
	= form_for [@itemable, @eventable, @item], remote: true do |f|
		= f.label :name
		= f.text_field :name
		= f.label :quantity_needed
		= f.text_field :quantity_needed
		= f.submit "Add Items", class: 'btn-large btn-success', style: 'padding-bottom: 30px !important;'

app/views/items/create.js.erb
$('.add-item-form-container').fadeOut()
$overlay.remove();
// $('.created-volunteers').html('<%= j render("volunteers/volunteer") %>').hide().fadeIn()
$('.created-items').html('<%= j render("items/item") %>').hide().fadeIn()

app/views/items/edit.html.haml
%h1 Items#edit
%p Find me in app/views/items/edit.html.haml

app/views/items/new.js.erb
$('.add-item-form-container').html('<%= j render("items/new") %>').hide().fadeIn();
var $overlay = $('<div class="overlay">');
$overlay.appendTo("body").hide().fadeIn();
$overlay.on('click', function(e){
	$overlay.remove();
	$('.add-item-form-container').fadeOut();

});

app/views/items/show.html.haml
= @item.name
= link_to 'delete', user_event_item_path, method: :delete

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EventerApp"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    %script{src: "//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"}
    %link{href: "http://fonts.googleapis.com/css?family=Julius+Sans+One|Open+Sans+Condensed:300", rel: "stylesheet", type: "text/css"}
  %body
    #navbar-container{style: 'font-size: 17px;'}
      .container
        .row
          .span5
            = link_to "EventApp", root_path, class: 'logo'
          .span7.pull-right
            %ul#nav-bar.pull-right{style: 'position: relative;'}
              %li
                = link_to 'Home', root_path
              %li
                = link_to 'Learn more', static_pages_learn_path
              %li
                - if current_user
                  = link_to 'My Events', current_user
                - else
                  = link_to 'Join', new_user_registration_path
              - if current_user
                %li= link_to "Sign Out", destroy_user_session_path, :method => :delete
              - else
                %li
                  %span.hover-login
                    = link_to 'Login', "#", class: 'nav-login-button'
                    #login-form 
                      %br
                      = form_for("user", :url => user_session_path) do |f|
                        = f.label :email
                        = f.email_field :email, style: 'width: 385px !important;'
                        = f.label :password
                        = f.password_field :password, style: 'width: 385px !important;'
                        = f.submit "Sign in", class: 'btn-info btn-small'
                        Not a memeber?  
                        = link_to 'Sign Up', new_user_registration_path
                  / .mac
                  /   Im a Mac
                  / .pc
                  /   Im a PC
    = yield 
    #bottom-footer
      .container
        .row
          .span4
            Copyright 2013 Yo Mamma

app/views/static_pages/home.html.haml
#video-viewport{style: 'background: black;'}
  = video_tag "grainvideo.mov", :size => "1280x720", :controls => true, id: 'video', autoplay: "", controls: "", loop: true
  .container
    #banner-content
      %h2{style: "font-size: 30px;"} Plan Your Next Event
      %p{style: 'font-size: 15px; line-height:22px;'} Lorem ipsum dolor sitta upsum dolor.  Lorem ipsum dolor sitta upsum dolor.  Lorem ipsum dolor sitta upsum dolor.
      .transparent-button
        = link_to 'Sign Up', new_user_registration_path, style: 'color: white;'
      .solid-button
        - if current_user.present?
          = link_to 'Create Event', new_user_event_path(current_user), style: 'color: white;'
        - else
          = link_to 'Create Event', new_user_registration_path, style: 'color: white;'
#body-content
  %br
  .container
    .row
      .span3
        .cirlce
          .span.icon-star{style: 'position: relative; right: 20px; top: 8px;'}
        .span{style: 'float: left; font-family:"Open Sans Condensed", sans-serif; font-size: 20px; margin-top: 22px; position: relative; right: 20px;'}
          %strong
            Lorem Ipsum dolor sitta
        .span{style: 'text-align: left; margin-top: 10px; font-family:"Open Sans Condensed"; position: relative; right: 25px;'}
          Lorem ipsum dolor sitta.  Ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta.
      .span3
        .cirlce
          .span.icon-heart{style: 'position: relative; right: 20px; top: 8px;'}
        .span{style: 'float: left; font-family:"Open Sans Condensed", sans-serif; font-size: 20px; margin-top: 22px; position: relative; right: 20px;'}
          %strong
            Lorem Ipsum dolor sitta
        .span{style: 'text-align: left; margin-top: 10px; font-family:"Open Sans Condensed"; position: relative; right: 25px;'}
          Lorem ipsum dolor sitta.  Ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta.
      .span3
        .cirlce
          .span.icon-off{style: 'position: relative; right: 20px; top: 8px;'}
        .span{style: 'float: left; font-family:"Open Sans Condensed", sans-serif; font-size: 20px; margin-top: 22px; position: relative; right: 20px;'}
          %strong
            Lorem Ipsum dolor sitta
        .span{style: 'text-align: left; margin-top: 10px; font-family:"Open Sans Condensed"; position: relative; right: 25px;'}
          Lorem ipsum dolor sitta.  Ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta.
      .span3
        .cirlce
          .span.icon-comment{style: 'position: relative; right: 20px; top: 8px;'}
        .span{style: 'float: left; font-family:"Open Sans Condensed", sans-serif; font-size: 20px; margin-top: 22px; position: relative; right: 20px;'}
          %strong
            Lorem Ipsum dolor sitta
        .span{style: 'text-align: left; margin-top: 10px; font-family:"Open Sans Condensed"; position: relative; right: 25px;'}
          Lorem ipsum dolor sitta.  Ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta.
  #mid-content
    %h2 Let Us Help You Plan Your Next Amazing Event


  %br
  .container
    .row
      .span5{style: 'margin-right: 170px;'}
        .span{style: 'float: left; font-family:"Open Sans Condensed", sans-serif; font-size: 20px; margin-top: 22px; position: relative; right: 20px; text-align: left;'}
          %strong
            Lorem Ipsum dolor sitta ipsum dolor sitta?
          %hr
          %p{style: 'color: #888888; font-size: 15px;'} Lorem ipsum dolor sitta.  Ipsum dolor sitta lorem ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta lorem ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta lorem ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta lorem ipsum dolor sitta.  Lorem ipsum dolor sitta.  Ipsum dolor sitta lorem ipsum dolor sitta.
        
          = link_to "Learn More", '#', class: 'btn btn-success'
      .span5{style: 'margin-top: 20px;'}
        = image_tag 'american.jpg'

  #bottom-footer
    .container
      .row
        .span4
          Copyright 2013 Yo Mamma

app/views/static_pages/learn.html.haml
%h2 Hello

app/views/users/edit.html.haml
= form_for @user, :multipart => true do |f|
	= f.label :name
	= f.text_field :name
	= f.label :email
	= f.text_field :email
	= f.label :profile_pic
	= f.file_field :profile_pic
	= f.label :password
	= f.text_field :password
	= f.label :password_confirmation
	= f.text_field :password_confirmation
	%br
	= f.submit 

app/views/users/show.html.haml
.container{style: 'margin-top: 60px;'}
	= image_tag @user.profile_pic, style: 'width: 100px; float: left; margin-right: 10px;'
	= @user.name
	%br
	= @user.email

app/views/volunteers/_form.html.haml
= form_for [@volunteerable, @events, @items, @volunteer], remote: true, :html => { :multipart => true } do |f|
	%br
	%h3 Thank You For Volunteering!
	= f.label :name
	= f.text_field :name, style: 'width: 400px !important;'
	= f.label :quantity_given
	= f.text_field :quantity_given, style: 'width: 400px !important;'
	/ = f.label :profile_pic
	/ = f.file_field :profile_pic
	= f.submit 'Volunteer', remote: true, class: 'btn-success btn-small', style: 'width: 415px !important;'
= link_to 'cancel', '#' ,class: 'cancel-volunteer'
%br
%br

app/views/volunteers/_volunteer.html.haml
%br
%h4 Volunteers
- @items.each do |item|
	- if item.volunteers.present?
		%strong
			= item.name
		- item.volunteers.each do |volunteer|
			%ul
				%li 
					/ = image_tag volunteer.profile_pic, style: 'width: 50px; float: left; margin-right: 10px; margin-top: 4px;'
					= volunteer.name
					is bringing
					= volunteer.quantity_given
					= item.name
					%br
					%span{style: 'font-size: 10px;'}
						- from_time = volunteer.created_at
						= time_ago_in_words(from_time)
						ago
				%br			
		%hr
	- else
		%strong
			= item.name
		%br
		We need Volunteers for this
		%br
		%hr

app/views/volunteers/create.js.erb
$(".new_volunteer").hide()
// $('.created-volunteers').html('<%= j render("volunteer") %>').hide().fadeIn()
$('.created-items').load('<%= j render("items/item") %>');

app/views/volunteers/edit.html.haml
%h1 Volunteers#edit
%p Find me in app/views/volunteers/edit.html.haml

app/views/volunteers/index.html.haml
%h1 Volunteers#index
%p Find me in app/views/volunteers/index.html.haml

app/views/volunteers/new.html.haml
= form_for [@volunteerable, @events, @items, @volunteer], :html => { :multipart => true } do |f|
	= f.label :name
	= f.text_field :name	
	= f.label :quantity_given
	= f.text_field :quantity_given
	= f.submit

app/views/volunteers/new.js.erb
$("#volunteer-<%= @items.id %>").html('<%= j render("volunteers/form") %>').hide().fadeIn("500")

app/views/volunteers/show.html.haml
%h1 Volunteers#show
%p Find me in app/views/volunteers/show.html.haml